services:
  front:
    container_name: front
    image: 'psr-frontend'
    build:
      context: ./
      dockerfile: ./front/Dockerfile
    depends_on:
      - back
    volumes:
      - .:/home/jan/PycharmProjects/projektowanie-systemow-rozproszonych/
    ports:
      - "8555:8555"
  back:
    container_name: back
    image: 'psr-backend'
    build:
      context: ./
      dockerfile: ./back/Dockerfile
    volumes:
      - .:/home/jan/PycharmProjects/projektowanie-systemow-rozproszonych/
    depends_on:
      - registry
    ports:
      - "8001:8001"
      - "443:8002"
  registry:
    container_name: registry
    image: 'psr-registry'
    build:
      context: ./
      dockerfile: ./registry/Dockerfile
    ports:
      - "8000:8000"