apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: registry
        image: zbsiregistry.azurecr.io/registry:latest
        ports:
        - containerPort: 8001
          name: back
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: registry
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: back
        image: zbsiregistry.azurecr.io/back:latest
        ports:
        - containerPort: 8001
          name: back
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: back
spec:
  ports:
  - port: 8001
    targetPort: 8001
  selector:
    app: back
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: front
        image: zbsiregistry.azurecr.io/front:latest
        ports:
        - containerPort: 8555
          name: front
        resources:
          requests:
            cpu: 1m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  ports:
  - port: 8555
    targetPort: 8555
  selector:
    app: front
  type: LoadBalancer